"use client";

import { TransitionProvider } from "@/components/context/TransitionContext";
import "./globals.scss";
import { Open_Sans } from "next/font/google";
import { SmoothScroll } from "@/components/layout/SmoothScroll";
import { motion } from "framer-motion";
import Cursor from "@/components/cursor/Cursor";
import { useRef, useEffect, useState } from "react";
import Footer from "@/components/sections/Footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const bodyRef = useRef<HTMLBodyElement>(null);

	return (
		<html lang="en">
			<body
				className={`${openSans.className}`}
				ref={bodyRef}
			>
				<div className="background"></div>
				<TransitionProvider>
					<SmoothScroll>
						{children}
						<Footer />
					</SmoothScroll>
				</TransitionProvider>
				<Cursor />
			</body>
		</html>
	);
}
